### ISSUE TITLE
PCA plot

### ISSUE THREAD

**Issue by francaklaeren** [datascience-mobi-2023/topic05_team02#3]
I wrote the following code:

library(pls)
install.packages ('ggfortify')
library(ggfortify)
install.packages("factoextra")
library(factoextra)
#PCA over the genes in exp
pca_exp_genes = prcomp(t(prism.exp), center = FALSE, scale = FALSE)
pca_cnv_genes= prcomp(t(prism.cnv), center= FALSE, scale= FALSE)
autoplot(pca_cnv,
         data= t(prism.cnv),
         colour= rainbow(27562))
#PCA over the cell lines in exp
pca_exp_celllines=prcomp(prism.exp, center=FALSE, scale=FALSE)
autoplot(pca_exp_celllines,
         data=prism.exp,
         colour= rainbow(477)))

now, I don't want to have a different colour per cellline but per cancer type, so I created a list with the celllines per cancertype:
#Vektor mit Zelllinien pro cancertype für colouring
celllines <- list()
# Loop over the cancertypes vector
for (cancertype in cancertypes) {
  # Subset the prism.cl data frame for the current cancer type
  cancer_df <- rownames(prism.cl[which(prism.cl$disease == cancertype), ])
  
  # Subset the prism.exp data frame based on the row names from the cancer_df
  celllines[[cancertype]] <- cancer_df
}

I tried to implement this as the colouring vector in many different ways amongst others with the function as.factor, but a list cannot be turned into an integer and I can't find out how to get the colouring per cancertype as well as the legend on the side...

**Comment by aluisascosta** [comment]
I figured that since you are using ggplot you know how to handle such plots. Rather than using this approach, you can first extract the actual PCA output and then just use the lineage to colour the dots. 

```
celllines = prism.cl[,c(1,6)]
celllines = celllines[celllines$DepMap_ID %in% rownames(prism.exp),]


# Make another df
toplot = as.data.frame(pca_exp_celllines$x) 
toplot$DepMap_ID = rownames(toplot)

plot_wCells = merge(toplot, celllines, by = "DepMap_ID")

# Plot
ggplot(plot_wCells, 
       aes(x = PC1, y = PC2, color = lineage)) +
  geom_point() 

```
