### ISSUE TITLE
Statistical tests

### ISSUE THREAD

**Issue by francaklaeren** [datascience-mobi-2023/topic05_team02#5]
I applied a Kolmogorov-Smirnov test and a qqplot against a normal distribution with the same mean to test for the normality of the distribution of correlation values of kidney cancer.
They give me compleatly different results... a Shapiro wilks test is not possible as the sample size exceeds 5000. 

qqplot(rnorm(18560,mean=mean(kidney_cor, na.rm = TRUE)),kidney_cor)
ks.test(kidney_cor, "pnorm", mean=mean(kidney_cor, na.rm = TRUE))

**Comment by aluisascosta** [comment]
You can use other tests which were not covered in the WiSe course but add in some information about them in your report when you are applying them. 
Here is some information on this one: https://www.itl.nist.gov/div898/handbook/eda/section3/eda35g.htm
